"""empty message

Revision ID: 15cda8d226ff
Revises: d4ef3547a228
Create Date: 2021-08-25 09:22:27.164498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15cda8d226ff'
down_revision = 'd4ef3547a228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('lastname', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('_password', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.VARCHAR(), nullable=False),
    sa.Column('ciudad', sa.VARCHAR(), nullable=False),
    sa.Column('cp', sa.VARCHAR(), nullable=False),
    sa.Column('is_barber', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('ciudad'),
    sa.UniqueConstraint('cp'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_password', sa.VARCHAR(), nullable=False),
    sa.Column('radio', sa.Integer(), nullable=False),
    sa.Column('id_coustomer', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_coustomer'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barber_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('tiempo', sa.Integer(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('id_barber', sa.Integer(), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_barber'], ['barber.id'], ),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('id_account', sa.Integer(), nullable=True),
    sa.Column('id_barber', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_barber'], ['barber.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_cita', sa.Date(), nullable=False),
    sa.Column('id_barber_servicio', sa.Integer(), nullable=True),
    sa.Column('id_account', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_account'], ['account.id'], ),
    sa.ForeignKeyConstraint(['id_barber_servicio'], ['barber_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('cita')
    op.drop_table('review')
    op.drop_table('barber_servicio')
    op.drop_table('barber')
    op.drop_table('servicios')
    op.drop_table('account')
    # ### end Alembic commands ###
