"""empty message

Revision ID: 56e64e7783d3
Revises: 7569c2afbc1c
Create Date: 2021-08-25 14:20:25.889728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e64e7783d3'
down_revision = '7569c2afbc1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('id_barber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_barber'], ['barber.id'], ),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
