"""empty message

Revision ID: de54c8340e36
Revises: 57eabe6fbc9c
Create Date: 2021-09-07 13:06:52.471579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de54c8340e36'
down_revision = '57eabe6fbc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barberServices', sa.Column('start_hour', sa.DateTime(), nullable=False))
    op.add_column('barberServices', sa.Column('end_hour', sa.DateTime(), nullable=False))
    op.add_column('barberServices', sa.Column('monday', sa.Boolean(), nullable=True))
    op.add_column('barberServices', sa.Column('tuesday', sa.Boolean(), nullable=True))
    op.add_column('barberServices', sa.Column('wednesday', sa.Boolean(), nullable=True))
    op.add_column('barberServices', sa.Column('thursday', sa.Boolean(), nullable=True))
    op.add_column('barberServices', sa.Column('friday', sa.Boolean(), nullable=True))
    op.add_column('barberServices', sa.Column('saturday', sa.Boolean(), nullable=True))
    op.add_column('barberServices', sa.Column('sunday', sa.Boolean(), nullable=True))
    op.add_column('barberServices', sa.Column('category', sa.Enum(), nullable=False))
    op.alter_column('barberServices', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('barberServices', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barberServices', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('barberServices', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('barberServices', 'category')
    op.drop_column('barberServices', 'sunday')
    op.drop_column('barberServices', 'saturday')
    op.drop_column('barberServices', 'friday')
    op.drop_column('barberServices', 'thursday')
    op.drop_column('barberServices', 'wednesday')
    op.drop_column('barberServices', 'tuesday')
    op.drop_column('barberServices', 'monday')
    op.drop_column('barberServices', 'end_hour')
    op.drop_column('barberServices', 'start_hour')
    # ### end Alembic commands ###
