"""empty message

Revision ID: eb494c017a1b
Revises: 7dbaa2ecfb56
Create Date: 2021-08-25 14:16:40.681812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb494c017a1b'
down_revision = '7dbaa2ecfb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barberServices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('id_barber', sa.Integer(), nullable=True),
    sa.Column('id_services', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_barber'], ['barber.id'], ),
    sa.ForeignKeyConstraint(['id_services'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barberServices')
    op.drop_table('services')
    # ### end Alembic commands ###
